### PR TITLE
Edited XML to include likes and comments of Companys' shares.

### PR DESCRIPTION
**Pull request by RayyanTahir**

### CODE REVIEW

**Comment by sandrock** [comment]
Hello. Thank you for your PR.

Before integrating and making a build, I have a few questions about your changes.

GetShares method
--------------

You changed the GetShares method, removing both pagination and event-types. I understand you may want to remove event-types. 

Q1. Why did you remove the pagination? 

I suggest the following overloads. Both method will have pagination. One will filter by event-type.

    <ApiMethod MethodName="GetShares" HttpMethod="GET" Path="/v1/companies/{int id}/updates?start={int start}&amp;count={int count}" ReturnType="CompanyUpdates"
      Title="Retrieve the company's updates"
      RequiresUserAuthentication="1" />
    <ApiMethod MethodName="GetShares" HttpMethod="GET" Path="/v1/companies/{int id}/updates?start={int start}&amp;count={int count}&amp;event-type={type}" ReturnType="CompanyUpdates"
      Title="Retrieve the company's updates"
      Remark="event-type: job-posting, new-product, status-update"
      RequiresUserAuthentication="1" />

GetBasicCompany method
------------------------

The doc says

> You can also fetch a list of all companies the authenticated user is an administrator of

Q2. Do you agree that a better name would be `GetAdministratingList`?

CompanyUpdate return type
-------------------------------------

    <Field Name="updateComments" Type="CompanyUpdateComments"/>
    <Field Name="likes" Type="CompanyUpdateComments"/>

Q3. I suppose there is an error in this code?

Tests
----------

Q4. Have you tested this code? Or is it just a feature request with a draft of code?

**Comment by RayyanTahir** [comment]
Hey, thanks for your comment on my PR.

**GetShares Method**
I removed the pagination because i was getting errors when providing start = 0 and count = 5000. Maybe the count was too high. I'll rollback that method to bring pagination back.

**GetBasicCompany Method**
I was using probably a different version of this library before and it had the method GetBasicCompany. But this version had this method removed (don't know why). So i brought that back again. Yes let's rename it. My suggestion is: "GetCompaniesList".

**CompanyUpdate return type**
I see the error (Wrong type):
`<Field Name="likes" Type="CompanyUpdateComments"/>`

**Tests**
Please deny these changes. I'll fix them, test them and send a pull request again. Many thanks for your suggestions.

**Comment by sandrock** [comment]
Ok.

I'm already integrating some of your changes in [this branch](https://github.com/SparkleNetworks/LinkedInNET/tree/pr/11). You shall wait before making further changes on *these* subjects.

**Comment by sandrock** [comment]
You may now get the latest stuff and PR from that if you feel for it.

**Comment by RayyanTahir** [comment]
Many thanks.

**Pull request merged**
